/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pltu.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['tripo_node_72e8fe26-34df-4f51-aa23-6f372e7a1a97']: THREE.Mesh
  }
  materials: {
    ['tripo_material_72e8fe26-34df-4f51-aa23-6f372e7a1a97']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/pltu.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_72e8fe26-34df-4f51-aa23-6f372e7a1a97'].geometry} material={materials['tripo_material_72e8fe26-34df-4f51-aa23-6f372e7a1a97']} />
    </group>
  )
}

useGLTF.preload('/models/pltu.glb')
